# a=set()
b=int(input("enter a no\t"))
# # a.add(b)
c=int(input("en)ter another no\t"))
# a.add(c)
d=int(input("enter another no\t"))
# a.add(d)
e=int(input("enter another no\t"))
# a.add(e)
f=int(input("enter another no\t"))
# a.add(f)
g=int(input("enter another no\t"))
# a.add(g)
h=int(input("enter another no\t"))
# a.add(h)
i=int(input("enter another no\t"))
# a.add(i)
a={b,c,d,e,f,g,h,i}
print(a)